apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediamtx.fullname" . }}
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rtsp }}
      targetPort: rtsp
      protocol: TCP
      name: rtsp
    - port: {{ .Values.service.rtmp }}
      targetPort: rtmp
      protocol: TCP
      name: rtmp
    - port: {{ .Values.service.hls }}
      targetPort: hls
      protocol: TCP
      name: hls
    - port: {{ .Values.service.webrtc }}
      targetPort: webrtc
      protocol: TCP
      name: webrtc
    - port: {{ .Values.service.srt }}
      targetPort: srt
      protocol: UDP
      name: srt
    - port: {{ .Values.service.api }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "mediamtx.selectorLabels" . | nindent 4 }}
