{{- if .Values.cameraUI.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homebridge.fullname" . }}-camera-ui-config
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.cameraUI.config | toPrettyJson | nindent 4 }}
{{- end }}
