apiVersion: v1
kind: Service
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.cameraUI.enabled }}
    - port: {{ .Values.cameraUI.port }}
      targetPort: {{ .Values.cameraUI.port }}
      protocol: TCP
      name: camera-ui
    {{- end }}
  selector:
    {{- include "homebridge.selectorLabels" . | nindent 4 }}
